version: 0.0
os: linux
# パーミッションと ower を指定できるか
files:
  - source: ./app.jar
    destination: /var/run/
  - source: ./sampleapp
    destination: /etc/sampleapp
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: batch-sample
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
